version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key
            tests:
            - unique
            - not_null
      - name: sales
        identifier: raw_gz_sales
        description: sales

        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness:
          warn_after:
            count: 90
            period: day

      - name: ship
        identifier: raw_gz_ship
        description: ships
        columns:
          - name: orders_id
            description: primary key
            tests:
            - unique
            - not_null