version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products
      - name: sales
        identifier: raw_gz_sales
        description: sales
      - name: ship
        identifier: raw_gz_ship
        description: ships